### ISSUE TITLE
Bug: KVS PANIC

### ISSUE THREAD

**Issue by joshuajohncohen** [kxtzownsu/KVS#1]
I found that KVS doesn't work on 125 (latest stable) so I tried downgrading to 120 to see if it would work on it. I found it still doesn't work on 120 (I am using octopus board) (Dell 3100 2-in-1 specifically), but in the process I found a bug. Photo is below.
![IMG_1608](https://github.com/user-attachments/assets/dab94cb5-fe25-48d3-95e9-3dc13896147c)
I am using an older version but the only changes since then are to the readme and website.

**Comment by kxtzownsu** [comment]
hmmm, i'll check the scripts in a second, i don't see why it would panic like that

edit: you don't need to back up your kernver by the way, if you need to set it back to KV3, just select it in the first menu option

**Comment by joshuajohncohen** [comment]
Got it, thanks!

Is there any possibility of ever supporting newer versions or has google just made the TPM commands used stop working with a TPM update, meaning it can never be used once a chromebook has updated past a certain version?

**Comment by kxtzownsu** [comment]
> Got it, thanks!
> 
> Is there any possibility of ever supporting newer versions or has google just made the TPM commands used stop working with a TPM update, meaning it can never be used once a chromebook has updated past a certain version?

Well, this project was made when KV3 was the newest version, so if your kernver is past that, it'll just error out on boot.

Google's Cr50/Ti50 TPM2 implementation also stops writing to the 0x1008 index if FWMP is enabled, unfortunately.

Edit: KVS2 (when it releases), should support all kernel versions due to it parsing the kernver's differently.

**Comment by joshuajohncohen** [comment]
Got it.

Thanks for the quick answer!

**Comment by JackWagon885** [comment]
hold up is KVS2 out yet or is KVS just patched on k4+

**Comment by kxtzownsu** [comment]
> hold up is KVS2 out yet or is KVS just patched on k4+

1) don't necropost
2) yes its been out for months
3) kvs will never be patched as long as you're unenrolled, there's too many methods (unenrolled only)
